// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: coord.proto

#include "coord.pb.h"
#include "coord.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace coord {

static const char* SNSCoordinator_method_names[] = {
  "/coord.SNSCoordinator/ClientLogin",
  "/coord.SNSCoordinator/ServerCommunicate",
  "/coord.SNSCoordinator/GetSlave",
  "/coord.SNSCoordinator/GetFsync",
};

std::unique_ptr< SNSCoordinator::Stub> SNSCoordinator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SNSCoordinator::Stub> stub(new SNSCoordinator::Stub(channel, options));
  return stub;
}

SNSCoordinator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ClientLogin_(SNSCoordinator_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ServerCommunicate_(SNSCoordinator_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_GetSlave_(SNSCoordinator_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFsync_(SNSCoordinator_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SNSCoordinator::Stub::ClientLogin(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::coord::ClientReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClientLogin_, context, request, response);
}

void SNSCoordinator::Stub::async::ClientLogin(::grpc::ClientContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClientLogin_, context, request, response, std::move(f));
}

void SNSCoordinator::Stub::async::ClientLogin(::grpc::ClientContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClientLogin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coord::ClientReply>* SNSCoordinator::Stub::PrepareAsyncClientLoginRaw(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::coord::ClientReply, ::coord::ClientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClientLogin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::coord::ClientReply>* SNSCoordinator::Stub::AsyncClientLoginRaw(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClientLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::coord::HeartBeat, ::coord::HeartBeat>* SNSCoordinator::Stub::ServerCommunicateRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::coord::HeartBeat, ::coord::HeartBeat>::Create(channel_.get(), rpcmethod_ServerCommunicate_, context);
}

void SNSCoordinator::Stub::async::ServerCommunicate(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::coord::HeartBeat,::coord::HeartBeat>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::coord::HeartBeat,::coord::HeartBeat>::Create(stub_->channel_.get(), stub_->rpcmethod_ServerCommunicate_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::coord::HeartBeat, ::coord::HeartBeat>* SNSCoordinator::Stub::AsyncServerCommunicateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::coord::HeartBeat, ::coord::HeartBeat>::Create(channel_.get(), cq, rpcmethod_ServerCommunicate_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::coord::HeartBeat, ::coord::HeartBeat>* SNSCoordinator::Stub::PrepareAsyncServerCommunicateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::coord::HeartBeat, ::coord::HeartBeat>::Create(channel_.get(), cq, rpcmethod_ServerCommunicate_, context, false, nullptr);
}

::grpc::Status SNSCoordinator::Stub::GetSlave(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::coord::ClientReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSlave_, context, request, response);
}

void SNSCoordinator::Stub::async::GetSlave(::grpc::ClientContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSlave_, context, request, response, std::move(f));
}

void SNSCoordinator::Stub::async::GetSlave(::grpc::ClientContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSlave_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coord::ClientReply>* SNSCoordinator::Stub::PrepareAsyncGetSlaveRaw(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::coord::ClientReply, ::coord::ClientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSlave_, context, request);
}

::grpc::ClientAsyncResponseReader< ::coord::ClientReply>* SNSCoordinator::Stub::AsyncGetSlaveRaw(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSlaveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SNSCoordinator::Stub::GetFsync(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::coord::ClientReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFsync_, context, request, response);
}

void SNSCoordinator::Stub::async::GetFsync(::grpc::ClientContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFsync_, context, request, response, std::move(f));
}

void SNSCoordinator::Stub::async::GetFsync(::grpc::ClientContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFsync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coord::ClientReply>* SNSCoordinator::Stub::PrepareAsyncGetFsyncRaw(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::coord::ClientReply, ::coord::ClientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFsync_, context, request);
}

::grpc::ClientAsyncResponseReader< ::coord::ClientReply>* SNSCoordinator::Stub::AsyncGetFsyncRaw(::grpc::ClientContext* context, const ::coord::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFsyncRaw(context, request, cq);
  result->StartCall();
  return result;
}

SNSCoordinator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSCoordinator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSCoordinator::Service, ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSCoordinator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::coord::ClientRequest* req,
             ::coord::ClientReply* resp) {
               return service->ClientLogin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSCoordinator_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< SNSCoordinator::Service, ::coord::HeartBeat, ::coord::HeartBeat>(
          [](SNSCoordinator::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::coord::HeartBeat,
             ::coord::HeartBeat>* stream) {
               return service->ServerCommunicate(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSCoordinator_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSCoordinator::Service, ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSCoordinator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::coord::ClientRequest* req,
             ::coord::ClientReply* resp) {
               return service->GetSlave(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSCoordinator_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSCoordinator::Service, ::coord::ClientRequest, ::coord::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSCoordinator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::coord::ClientRequest* req,
             ::coord::ClientReply* resp) {
               return service->GetFsync(ctx, req, resp);
             }, this)));
}

SNSCoordinator::Service::~Service() {
}

::grpc::Status SNSCoordinator::Service::ClientLogin(::grpc::ServerContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSCoordinator::Service::ServerCommunicate(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::coord::HeartBeat, ::coord::HeartBeat>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSCoordinator::Service::GetSlave(::grpc::ServerContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSCoordinator::Service::GetFsync(::grpc::ServerContext* context, const ::coord::ClientRequest* request, ::coord::ClientReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace coord

