// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace service {

static const char* SNSServer_method_names[] = {
  "/service.SNSServer/Login",
  "/service.SNSServer/List",
  "/service.SNSServer/Follow",
  "/service.SNSServer/UnFollow",
  "/service.SNSServer/Timeline",
};

std::unique_ptr< SNSServer::Stub> SNSServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SNSServer::Stub> stub(new SNSServer::Stub(channel, options));
  return stub;
}

SNSServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(SNSServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_List_(SNSServer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Follow_(SNSServer_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnFollow_(SNSServer_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Timeline_(SNSServer_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status SNSServer::Stub::Login(::grpc::ClientContext* context, const ::service::Request& request, ::service::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void SNSServer::Stub::async::Login(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void SNSServer::Stub::async::Login(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::service::Reply, ::service::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SNSServer::Stub::List(::grpc::ClientContext* context, const ::service::Request& request, ::service::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_List_, context, request, response);
}

void SNSServer::Stub::async::List(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_List_, context, request, response, std::move(f));
}

void SNSServer::Stub::async::List(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_List_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::PrepareAsyncListRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::service::Reply, ::service::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_List_, context, request);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::AsyncListRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SNSServer::Stub::Follow(::grpc::ClientContext* context, const ::service::Request& request, ::service::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Follow_, context, request, response);
}

void SNSServer::Stub::async::Follow(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Follow_, context, request, response, std::move(f));
}

void SNSServer::Stub::async::Follow(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Follow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::PrepareAsyncFollowRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::service::Reply, ::service::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Follow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::AsyncFollowRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFollowRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SNSServer::Stub::UnFollow(::grpc::ClientContext* context, const ::service::Request& request, ::service::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnFollow_, context, request, response);
}

void SNSServer::Stub::async::UnFollow(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnFollow_, context, request, response, std::move(f));
}

void SNSServer::Stub::async::UnFollow(::grpc::ClientContext* context, const ::service::Request* request, ::service::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnFollow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::PrepareAsyncUnFollowRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::service::Reply, ::service::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnFollow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::service::Reply>* SNSServer::Stub::AsyncUnFollowRaw(::grpc::ClientContext* context, const ::service::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnFollowRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::service::Message, ::service::Message>* SNSServer::Stub::TimelineRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::service::Message, ::service::Message>::Create(channel_.get(), rpcmethod_Timeline_, context);
}

void SNSServer::Stub::async::Timeline(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::service::Message,::service::Message>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::service::Message,::service::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_Timeline_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::service::Message, ::service::Message>* SNSServer::Stub::AsyncTimelineRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::service::Message, ::service::Message>::Create(channel_.get(), cq, rpcmethod_Timeline_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::service::Message, ::service::Message>* SNSServer::Stub::PrepareAsyncTimelineRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::service::Message, ::service::Message>::Create(channel_.get(), cq, rpcmethod_Timeline_, context, false, nullptr);
}

SNSServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSServer::Service, ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::service::Request* req,
             ::service::Reply* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSServer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSServer::Service, ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::service::Request* req,
             ::service::Reply* resp) {
               return service->List(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSServer_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSServer::Service, ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::service::Request* req,
             ::service::Reply* resp) {
               return service->Follow(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSServer_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SNSServer::Service, ::service::Request, ::service::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SNSServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::service::Request* req,
             ::service::Reply* resp) {
               return service->UnFollow(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SNSServer_method_names[4],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< SNSServer::Service, ::service::Message, ::service::Message>(
          [](SNSServer::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::service::Message,
             ::service::Message>* stream) {
               return service->Timeline(ctx, stream);
             }, this)));
}

SNSServer::Service::~Service() {
}

::grpc::Status SNSServer::Service::Login(::grpc::ServerContext* context, const ::service::Request* request, ::service::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSServer::Service::List(::grpc::ServerContext* context, const ::service::Request* request, ::service::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSServer::Service::Follow(::grpc::ServerContext* context, const ::service::Request* request, ::service::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSServer::Service::UnFollow(::grpc::ServerContext* context, const ::service::Request* request, ::service::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SNSServer::Service::Timeline(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::Message, ::service::Message>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace service

